// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"AreYouOK/internal/model"
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newContactAttempt(db *gorm.DB, opts ...gen.DOOption) contactAttempt {
	_contactAttempt := contactAttempt{}

	_contactAttempt.contactAttemptDo.UseDB(db, opts...)
	_contactAttempt.contactAttemptDo.UseModel(&model.ContactAttempt{})

	tableName := _contactAttempt.contactAttemptDo.TableName()
	_contactAttempt.ALL = field.NewAsterisk(tableName)
	_contactAttempt.AttemptedAt = field.NewTime(tableName, "attempted_at")
	_contactAttempt.ResponseCode = field.NewString(tableName, "response_code")
	_contactAttempt.ResponseMessage = field.NewString(tableName, "response_message")
	_contactAttempt.ContactPhoneHash = field.NewString(tableName, "contact_phone_hash")
	_contactAttempt.Channel = field.NewString(tableName, "channel")
	_contactAttempt.Status = field.NewString(tableName, "status")
	_contactAttempt.CreatedAt = field.NewTime(tableName, "created_at")
	_contactAttempt.UpdatedAt = field.NewTime(tableName, "updated_at")
	_contactAttempt.DeletedAt = field.NewField(tableName, "deleted_at")
	_contactAttempt.ID = field.NewInt64(tableName, "id")
	_contactAttempt.TaskID = field.NewInt64(tableName, "task_id")
	_contactAttempt.ContactPriority = field.NewInt(tableName, "contact_priority")
	_contactAttempt.CostCents = field.NewInt(tableName, "cost_cents")
	_contactAttempt.Deducted = field.NewBool(tableName, "deducted")

	_contactAttempt.fillFieldMap()

	return _contactAttempt
}

type contactAttempt struct {
	contactAttemptDo

	ALL              field.Asterisk
	AttemptedAt      field.Time
	ResponseCode     field.String
	ResponseMessage  field.String
	ContactPhoneHash field.String
	Channel          field.String
	Status           field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	ID               field.Int64
	TaskID           field.Int64
	ContactPriority  field.Int
	CostCents        field.Int
	Deducted         field.Bool

	fieldMap map[string]field.Expr
}

func (c contactAttempt) Table(newTableName string) *contactAttempt {
	c.contactAttemptDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c contactAttempt) As(alias string) *contactAttempt {
	c.contactAttemptDo.DO = *(c.contactAttemptDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *contactAttempt) updateTableName(table string) *contactAttempt {
	c.ALL = field.NewAsterisk(table)
	c.AttemptedAt = field.NewTime(table, "attempted_at")
	c.ResponseCode = field.NewString(table, "response_code")
	c.ResponseMessage = field.NewString(table, "response_message")
	c.ContactPhoneHash = field.NewString(table, "contact_phone_hash")
	c.Channel = field.NewString(table, "channel")
	c.Status = field.NewString(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.DeletedAt = field.NewField(table, "deleted_at")
	c.ID = field.NewInt64(table, "id")
	c.TaskID = field.NewInt64(table, "task_id")
	c.ContactPriority = field.NewInt(table, "contact_priority")
	c.CostCents = field.NewInt(table, "cost_cents")
	c.Deducted = field.NewBool(table, "deducted")

	c.fillFieldMap()

	return c
}

func (c *contactAttempt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *contactAttempt) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["attempted_at"] = c.AttemptedAt
	c.fieldMap["response_code"] = c.ResponseCode
	c.fieldMap["response_message"] = c.ResponseMessage
	c.fieldMap["contact_phone_hash"] = c.ContactPhoneHash
	c.fieldMap["channel"] = c.Channel
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["deleted_at"] = c.DeletedAt
	c.fieldMap["id"] = c.ID
	c.fieldMap["task_id"] = c.TaskID
	c.fieldMap["contact_priority"] = c.ContactPriority
	c.fieldMap["cost_cents"] = c.CostCents
	c.fieldMap["deducted"] = c.Deducted
}

func (c contactAttempt) clone(db *gorm.DB) contactAttempt {
	c.contactAttemptDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c contactAttempt) replaceDB(db *gorm.DB) contactAttempt {
	c.contactAttemptDo.ReplaceDB(db)
	return c
}

type contactAttemptDo struct{ gen.DO }

type IContactAttemptDo interface {
	gen.SubQuery
	Debug() IContactAttemptDo
	WithContext(ctx context.Context) IContactAttemptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IContactAttemptDo
	WriteDB() IContactAttemptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IContactAttemptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IContactAttemptDo
	Not(conds ...gen.Condition) IContactAttemptDo
	Or(conds ...gen.Condition) IContactAttemptDo
	Select(conds ...field.Expr) IContactAttemptDo
	Where(conds ...gen.Condition) IContactAttemptDo
	Order(conds ...field.Expr) IContactAttemptDo
	Distinct(cols ...field.Expr) IContactAttemptDo
	Omit(cols ...field.Expr) IContactAttemptDo
	Join(table schema.Tabler, on ...field.Expr) IContactAttemptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IContactAttemptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IContactAttemptDo
	Group(cols ...field.Expr) IContactAttemptDo
	Having(conds ...gen.Condition) IContactAttemptDo
	Limit(limit int) IContactAttemptDo
	Offset(offset int) IContactAttemptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IContactAttemptDo
	Unscoped() IContactAttemptDo
	Create(values ...*model.ContactAttempt) error
	CreateInBatches(values []*model.ContactAttempt, batchSize int) error
	Save(values ...*model.ContactAttempt) error
	First() (*model.ContactAttempt, error)
	Take() (*model.ContactAttempt, error)
	Last() (*model.ContactAttempt, error)
	Find() ([]*model.ContactAttempt, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContactAttempt, err error)
	FindInBatches(result *[]*model.ContactAttempt, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ContactAttempt) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IContactAttemptDo
	Assign(attrs ...field.AssignExpr) IContactAttemptDo
	Joins(fields ...field.RelationField) IContactAttemptDo
	Preload(fields ...field.RelationField) IContactAttemptDo
	FirstOrInit() (*model.ContactAttempt, error)
	FirstOrCreate() (*model.ContactAttempt, error)
	FindByPage(offset int, limit int) (result []*model.ContactAttempt, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IContactAttemptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ListByTaskID(taskID int64) (result []*model.ContactAttempt, err error)
	ListByTaskIDAndStatus(taskID int64, status string) (result []*model.ContactAttempt, err error)
	CountByTaskID(taskID int64) (result int64, err error)
	GetLatestByTaskID(taskID int64) (result *model.ContactAttempt, err error)
}

// ListByTaskID 根据任务ID查询尝试记录
//
// SELECT * FROM @@table
// WHERE task_id = @taskID
// ORDER BY attempted_at DESC
func (c contactAttemptDo) ListByTaskID(taskID int64) (result []*model.ContactAttempt, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, taskID)
	generateSQL.WriteString("SELECT * FROM contact_attempts WHERE task_id = ? ORDER BY attempted_at DESC ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByTaskIDAndStatus 根据任务ID和状态查询尝试记录
//
// SELECT * FROM @@table
// WHERE task_id = @taskID
//
//	{{if status != ""}}
//	AND status = @status
//	{{end}}
//
// ORDER BY attempted_at DESC
func (c contactAttemptDo) ListByTaskIDAndStatus(taskID int64, status string) (result []*model.ContactAttempt, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, taskID)
	generateSQL.WriteString("SELECT * FROM contact_attempts WHERE task_id = ? ")
	if status != "" {
		params = append(params, status)
		generateSQL.WriteString("AND status = ? ")
	}
	generateSQL.WriteString("ORDER BY attempted_at DESC ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountByTaskID 统计任务的尝试次数
//
// SELECT COUNT(*) as count
// FROM @@table
// WHERE task_id = @taskID
func (c contactAttemptDo) CountByTaskID(taskID int64) (result int64, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, taskID)
	generateSQL.WriteString("SELECT COUNT(*) as count FROM contact_attempts WHERE task_id = ? ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetLatestByTaskID 获取任务最新的尝试记录
//
// SELECT * FROM @@table
// WHERE task_id = @taskID
// ORDER BY attempted_at DESC
// LIMIT 1
func (c contactAttemptDo) GetLatestByTaskID(taskID int64) (result *model.ContactAttempt, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, taskID)
	generateSQL.WriteString("SELECT * FROM contact_attempts WHERE task_id = ? ORDER BY attempted_at DESC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = c.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (c contactAttemptDo) Debug() IContactAttemptDo {
	return c.withDO(c.DO.Debug())
}

func (c contactAttemptDo) WithContext(ctx context.Context) IContactAttemptDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c contactAttemptDo) ReadDB() IContactAttemptDo {
	return c.Clauses(dbresolver.Read)
}

func (c contactAttemptDo) WriteDB() IContactAttemptDo {
	return c.Clauses(dbresolver.Write)
}

func (c contactAttemptDo) Session(config *gorm.Session) IContactAttemptDo {
	return c.withDO(c.DO.Session(config))
}

func (c contactAttemptDo) Clauses(conds ...clause.Expression) IContactAttemptDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c contactAttemptDo) Returning(value interface{}, columns ...string) IContactAttemptDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c contactAttemptDo) Not(conds ...gen.Condition) IContactAttemptDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c contactAttemptDo) Or(conds ...gen.Condition) IContactAttemptDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c contactAttemptDo) Select(conds ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c contactAttemptDo) Where(conds ...gen.Condition) IContactAttemptDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c contactAttemptDo) Order(conds ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c contactAttemptDo) Distinct(cols ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c contactAttemptDo) Omit(cols ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c contactAttemptDo) Join(table schema.Tabler, on ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c contactAttemptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c contactAttemptDo) RightJoin(table schema.Tabler, on ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c contactAttemptDo) Group(cols ...field.Expr) IContactAttemptDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c contactAttemptDo) Having(conds ...gen.Condition) IContactAttemptDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c contactAttemptDo) Limit(limit int) IContactAttemptDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c contactAttemptDo) Offset(offset int) IContactAttemptDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c contactAttemptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IContactAttemptDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c contactAttemptDo) Unscoped() IContactAttemptDo {
	return c.withDO(c.DO.Unscoped())
}

func (c contactAttemptDo) Create(values ...*model.ContactAttempt) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c contactAttemptDo) CreateInBatches(values []*model.ContactAttempt, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c contactAttemptDo) Save(values ...*model.ContactAttempt) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c contactAttemptDo) First() (*model.ContactAttempt, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactAttempt), nil
	}
}

func (c contactAttemptDo) Take() (*model.ContactAttempt, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactAttempt), nil
	}
}

func (c contactAttemptDo) Last() (*model.ContactAttempt, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactAttempt), nil
	}
}

func (c contactAttemptDo) Find() ([]*model.ContactAttempt, error) {
	result, err := c.DO.Find()
	return result.([]*model.ContactAttempt), err
}

func (c contactAttemptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ContactAttempt, err error) {
	buf := make([]*model.ContactAttempt, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c contactAttemptDo) FindInBatches(result *[]*model.ContactAttempt, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c contactAttemptDo) Attrs(attrs ...field.AssignExpr) IContactAttemptDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c contactAttemptDo) Assign(attrs ...field.AssignExpr) IContactAttemptDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c contactAttemptDo) Joins(fields ...field.RelationField) IContactAttemptDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c contactAttemptDo) Preload(fields ...field.RelationField) IContactAttemptDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c contactAttemptDo) FirstOrInit() (*model.ContactAttempt, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactAttempt), nil
	}
}

func (c contactAttemptDo) FirstOrCreate() (*model.ContactAttempt, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ContactAttempt), nil
	}
}

func (c contactAttemptDo) FindByPage(offset int, limit int) (result []*model.ContactAttempt, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c contactAttemptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c contactAttemptDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c contactAttemptDo) Delete(models ...*model.ContactAttempt) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *contactAttemptDo) withDO(do gen.Dao) *contactAttemptDo {
	c.DO = *do.(*gen.DO)
	return c
}
