// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                = new(Query) 
	DailyCheckIn     *dailyCheckIn
	Journey          *journey
	NotificationTask *notificationTask
	QuotaTransaction *quotaTransaction
	User             *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	DailyCheckIn = &Q.DailyCheckIn
	Journey = &Q.Journey
	NotificationTask = &Q.NotificationTask
	QuotaTransaction = &Q.QuotaTransaction
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:               db,
		DailyCheckIn:     newDailyCheckIn(db, opts...),
		Journey:          newJourney(db, opts...),
		NotificationTask: newNotificationTask(db, opts...),
		QuotaTransaction: newQuotaTransaction(db, opts...),
		User:             newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	DailyCheckIn     dailyCheckIn
	Journey          journey
	NotificationTask notificationTask
	QuotaTransaction quotaTransaction
	User             user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		DailyCheckIn:     q.DailyCheckIn.clone(db),
		Journey:          q.Journey.clone(db),
		NotificationTask: q.NotificationTask.clone(db),
		QuotaTransaction: q.QuotaTransaction.clone(db),
		User:             q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:               db,
		DailyCheckIn:     q.DailyCheckIn.replaceDB(db),
		Journey:          q.Journey.replaceDB(db),
		NotificationTask: q.NotificationTask.replaceDB(db),
		QuotaTransaction: q.QuotaTransaction.replaceDB(db),
		User:             q.User.replaceDB(db),
	}
}

type queryCtx struct {
	DailyCheckIn     IDailyCheckInDo
	Journey          IJourneyDo
	NotificationTask INotificationTaskDo
	QuotaTransaction IQuotaTransactionDo
	User             IUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		DailyCheckIn:     q.DailyCheckIn.WithContext(ctx),
		Journey:          q.Journey.WithContext(ctx),
		NotificationTask: q.NotificationTask.WithContext(ctx),
		QuotaTransaction: q.QuotaTransaction.WithContext(ctx),
		User:             q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
