// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"AreYouOK/internal/model"
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newJourney(db *gorm.DB, opts ...gen.DOOption) journey {
	_journey := journey{}

	_journey.journeyDo.UseDB(db, opts...)
	_journey.journeyDo.UseModel(&model.Journey{})

	tableName := _journey.journeyDo.TableName()
	_journey.ALL = field.NewAsterisk(tableName)
	_journey.ExpectedReturnTime = field.NewTime(tableName, "expected_return_time")
	_journey.ActualReturnTime = field.NewTime(tableName, "actual_return_time")
	_journey.ReminderSentAt = field.NewTime(tableName, "reminder_sent_at")
	_journey.AlertTriggeredAt = field.NewTime(tableName, "alert_triggered_at")
	_journey.AlertLastAttemptAt = field.NewTime(tableName, "alert_last_attempt_at")
	_journey.Title = field.NewString(tableName, "title")
	_journey.Note = field.NewString(tableName, "note")
	_journey.Status = field.NewString(tableName, "status")
	_journey.AlertStatus = field.NewString(tableName, "alert_status")
	_journey.CreatedAt = field.NewTime(tableName, "created_at")
	_journey.UpdatedAt = field.NewTime(tableName, "updated_at")
	_journey.DeletedAt = field.NewField(tableName, "deleted_at")
	_journey.ID = field.NewInt64(tableName, "id")
	_journey.UserID = field.NewInt64(tableName, "user_id")
	_journey.AlertAttempts = field.NewInt(tableName, "alert_attempts")

	_journey.fillFieldMap()

	return _journey
}

type journey struct {
	journeyDo

	ALL                field.Asterisk
	ExpectedReturnTime field.Time
	ActualReturnTime   field.Time
	ReminderSentAt     field.Time
	AlertTriggeredAt   field.Time
	AlertLastAttemptAt field.Time
	Title              field.String
	Note               field.String
	Status             field.String
	AlertStatus        field.String
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field
	ID                 field.Int64
	UserID             field.Int64
	AlertAttempts      field.Int

	fieldMap map[string]field.Expr
}

func (j journey) Table(newTableName string) *journey {
	j.journeyDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j journey) As(alias string) *journey {
	j.journeyDo.DO = *(j.journeyDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *journey) updateTableName(table string) *journey {
	j.ALL = field.NewAsterisk(table)
	j.ExpectedReturnTime = field.NewTime(table, "expected_return_time")
	j.ActualReturnTime = field.NewTime(table, "actual_return_time")
	j.ReminderSentAt = field.NewTime(table, "reminder_sent_at")
	j.AlertTriggeredAt = field.NewTime(table, "alert_triggered_at")
	j.AlertLastAttemptAt = field.NewTime(table, "alert_last_attempt_at")
	j.Title = field.NewString(table, "title")
	j.Note = field.NewString(table, "note")
	j.Status = field.NewString(table, "status")
	j.AlertStatus = field.NewString(table, "alert_status")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")
	j.ID = field.NewInt64(table, "id")
	j.UserID = field.NewInt64(table, "user_id")
	j.AlertAttempts = field.NewInt(table, "alert_attempts")

	j.fillFieldMap()

	return j
}

func (j *journey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *journey) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 15)
	j.fieldMap["expected_return_time"] = j.ExpectedReturnTime
	j.fieldMap["actual_return_time"] = j.ActualReturnTime
	j.fieldMap["reminder_sent_at"] = j.ReminderSentAt
	j.fieldMap["alert_triggered_at"] = j.AlertTriggeredAt
	j.fieldMap["alert_last_attempt_at"] = j.AlertLastAttemptAt
	j.fieldMap["title"] = j.Title
	j.fieldMap["note"] = j.Note
	j.fieldMap["status"] = j.Status
	j.fieldMap["alert_status"] = j.AlertStatus
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
	j.fieldMap["id"] = j.ID
	j.fieldMap["user_id"] = j.UserID
	j.fieldMap["alert_attempts"] = j.AlertAttempts
}

func (j journey) clone(db *gorm.DB) journey {
	j.journeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j journey) replaceDB(db *gorm.DB) journey {
	j.journeyDo.ReplaceDB(db)
	return j
}

type journeyDo struct{ gen.DO }

type IJourneyDo interface {
	gen.SubQuery
	Debug() IJourneyDo
	WithContext(ctx context.Context) IJourneyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJourneyDo
	WriteDB() IJourneyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJourneyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJourneyDo
	Not(conds ...gen.Condition) IJourneyDo
	Or(conds ...gen.Condition) IJourneyDo
	Select(conds ...field.Expr) IJourneyDo
	Where(conds ...gen.Condition) IJourneyDo
	Order(conds ...field.Expr) IJourneyDo
	Distinct(cols ...field.Expr) IJourneyDo
	Omit(cols ...field.Expr) IJourneyDo
	Join(table schema.Tabler, on ...field.Expr) IJourneyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJourneyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJourneyDo
	Group(cols ...field.Expr) IJourneyDo
	Having(conds ...gen.Condition) IJourneyDo
	Limit(limit int) IJourneyDo
	Offset(offset int) IJourneyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJourneyDo
	Unscoped() IJourneyDo
	Create(values ...*model.Journey) error
	CreateInBatches(values []*model.Journey, batchSize int) error
	Save(values ...*model.Journey) error
	First() (*model.Journey, error)
	Take() (*model.Journey, error)
	Last() (*model.Journey, error)
	Find() ([]*model.Journey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Journey, err error)
	FindInBatches(result *[]*model.Journey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Journey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJourneyDo
	Assign(attrs ...field.AssignExpr) IJourneyDo
	Joins(fields ...field.RelationField) IJourneyDo
	Preload(fields ...field.RelationField) IJourneyDo
	FirstOrInit() (*model.Journey, error)
	FirstOrCreate() (*model.Journey, error)
	FindByPage(offset int, limit int) (result []*model.Journey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJourneyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id int64) (result *model.Journey, err error)
	GetByPublicIDAndJourneyID(publicID int64, journeyID int64) (result *model.Journey, err error)
	ListByUserIDAndStatus(userID int64, status string, limit int, offset int) (result []*model.Journey, err error)
	ListByPublicIDAndStatus(publicID int64, status string, cursorID int64, limit int) (result []*model.Journey, err error)
	GetOngoingJourneyByUserID(userID int64) (result *model.Journey, err error)
	GetOngoingJourneyByPublicID(publicID int64) (result *model.Journey, err error)
	ListOngoingJourneys() (result []*model.Journey, err error)
	ListTimeoutJourneys() (result []*model.Journey, err error)
	CountByUserIDAndStatus(userID int64) (result []map[string]interface{}, err error)
}

// GetByID 根据数据库主键 ID 查询行程
//
// SELECT * FROM @@table WHERE id = @id LIMIT 1
func (j journeyDo) GetByID(id int64) (result *model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM journeys WHERE id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByPublicIDAndJourneyID 根据 PublicID 和 Journey ID 查询行程（API 常用）
//
// SELECT j.* FROM @@table j
// INNER JOIN users u ON u.id = j.user_id
// WHERE u.public_id = @publicID AND j.id = @journeyID
// LIMIT 1
func (j journeyDo) GetByPublicIDAndJourneyID(publicID int64, journeyID int64) (result *model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	params = append(params, journeyID)
	generateSQL.WriteString("SELECT j.* FROM journeys j INNER JOIN users u ON u.id = j.user_id WHERE u.public_id = ? AND j.id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByUserIDAndStatus 按用户和状态查询行程（分页）
//
// SELECT * FROM @@table
// WHERE user_id = @userID
//
//	{{if status != ""}}
//	AND status = @status
//	{{end}}
//
// ORDER BY created_at DESC
// LIMIT @limit OFFSET @offset
func (j journeyDo) ListByUserIDAndStatus(userID int64, status string, limit int, offset int) (result []*model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT * FROM journeys WHERE user_id = ? ")
	if status != "" {
		params = append(params, status)
		generateSQL.WriteString("AND status = ? ")
	}
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("ORDER BY created_at DESC LIMIT ? OFFSET ? ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByPublicIDAndStatus 根据 PublicID 和状态查询行程（API 常用，支持游标分页）
//
// SELECT j.* FROM @@table j
// INNER JOIN users u ON u.id = j.user_id
// WHERE u.public_id = @publicID
//
//	{{if status != ""}}
//	AND j.status = @status
//	{{end}}
//	{{if cursorID > 0}}
//	AND j.id < @cursorID
//	{{end}}
//
// ORDER BY j.created_at DESC
// LIMIT @limit
func (j journeyDo) ListByPublicIDAndStatus(publicID int64, status string, cursorID int64, limit int) (result []*model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	generateSQL.WriteString("SELECT j.* FROM journeys j INNER JOIN users u ON u.id = j.user_id WHERE u.public_id = ? ")
	if status != "" {
		params = append(params, status)
		generateSQL.WriteString("AND j.status = ? ")
	}
	if cursorID > 0 {
		params = append(params, cursorID)
		generateSQL.WriteString("AND j.id < ? ")
	}
	params = append(params, limit)
	generateSQL.WriteString("ORDER BY j.created_at DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetOngoingJourneyByUserID 查询用户进行中的行程（用于检查行程重叠）
//
// SELECT * FROM @@table
// WHERE user_id = @userID
//
//	AND status = 'ongoing'
//
// ORDER BY expected_return_time ASC
// LIMIT 1
func (j journeyDo) GetOngoingJourneyByUserID(userID int64) (result *model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT * FROM journeys WHERE user_id = ? AND status = 'ongoing' ORDER BY expected_return_time ASC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetOngoingJourneyByPublicID 根据 PublicID 查询用户进行中的行程（API 常用）
//
// SELECT j.* FROM @@table j
// INNER JOIN users u ON u.id = j.user_id
// WHERE u.public_id = @publicID
//
//	AND j.status = 'ongoing'
//
// ORDER BY j.expected_return_time ASC
// LIMIT 1
func (j journeyDo) GetOngoingJourneyByPublicID(publicID int64) (result *model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	generateSQL.WriteString("SELECT j.* FROM journeys j INNER JOIN users u ON u.id = j.user_id WHERE u.public_id = ? AND j.status = 'ongoing' ORDER BY j.expected_return_time ASC LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetOngoingJourneys 查询进行中的行程（用于定时任务）
//
// SELECT * FROM @@table
// WHERE status = 'ongoing'
//
//	AND expected_return_time < NOW()
func (j journeyDo) ListOngoingJourneys() (result []*model.Journey, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM journeys WHERE status = 'ongoing' AND expected_return_time < NOW() ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListTimeoutJourneys 查询超时的行程（用于定时任务）
//
// SELECT * FROM @@table
// WHERE status = 'ongoing'
//
//	AND expected_return_time < NOW() - INTERVAL '10 minutes'
func (j journeyDo) ListTimeoutJourneys() (result []*model.Journey, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM journeys WHERE status = 'ongoing' AND expected_return_time < NOW() - INTERVAL '10 minutes' ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountByUserIDAndStatus 统计用户行程数量（按状态）
//
// SELECT status, COUNT(*) as count
// FROM @@table
// WHERE user_id = @userID
// GROUP BY status
func (j journeyDo) CountByUserIDAndStatus(userID int64) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT status, COUNT(*) as count FROM journeys WHERE user_id = ? GROUP BY status ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (j journeyDo) Debug() IJourneyDo {
	return j.withDO(j.DO.Debug())
}

func (j journeyDo) WithContext(ctx context.Context) IJourneyDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j journeyDo) ReadDB() IJourneyDo {
	return j.Clauses(dbresolver.Read)
}

func (j journeyDo) WriteDB() IJourneyDo {
	return j.Clauses(dbresolver.Write)
}

func (j journeyDo) Session(config *gorm.Session) IJourneyDo {
	return j.withDO(j.DO.Session(config))
}

func (j journeyDo) Clauses(conds ...clause.Expression) IJourneyDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j journeyDo) Returning(value interface{}, columns ...string) IJourneyDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j journeyDo) Not(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j journeyDo) Or(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j journeyDo) Select(conds ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j journeyDo) Where(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j journeyDo) Order(conds ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j journeyDo) Distinct(cols ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j journeyDo) Omit(cols ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j journeyDo) Join(table schema.Tabler, on ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j journeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j journeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j journeyDo) Group(cols ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j journeyDo) Having(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j journeyDo) Limit(limit int) IJourneyDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j journeyDo) Offset(offset int) IJourneyDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j journeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJourneyDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j journeyDo) Unscoped() IJourneyDo {
	return j.withDO(j.DO.Unscoped())
}

func (j journeyDo) Create(values ...*model.Journey) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j journeyDo) CreateInBatches(values []*model.Journey, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j journeyDo) Save(values ...*model.Journey) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j journeyDo) First() (*model.Journey, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) Take() (*model.Journey, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) Last() (*model.Journey, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) Find() ([]*model.Journey, error) {
	result, err := j.DO.Find()
	return result.([]*model.Journey), err
}

func (j journeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Journey, err error) {
	buf := make([]*model.Journey, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j journeyDo) FindInBatches(result *[]*model.Journey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j journeyDo) Attrs(attrs ...field.AssignExpr) IJourneyDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j journeyDo) Assign(attrs ...field.AssignExpr) IJourneyDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j journeyDo) Joins(fields ...field.RelationField) IJourneyDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j journeyDo) Preload(fields ...field.RelationField) IJourneyDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j journeyDo) FirstOrInit() (*model.Journey, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) FirstOrCreate() (*model.Journey, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) FindByPage(offset int, limit int) (result []*model.Journey, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j journeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j journeyDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j journeyDo) Delete(models ...*model.Journey) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *journeyDo) withDO(do gen.Dao) *journeyDo {
	j.DO = *do.(*gen.DO)
	return j
}
