// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"AreYouOK/internal/repository/model"
)

func newJourney(db *gorm.DB, opts ...gen.DOOption) journey {
	_journey := journey{}

	_journey.journeyDo.UseDB(db, opts...)
	_journey.journeyDo.UseModel(&model.Journey{})

	tableName := _journey.journeyDo.TableName()
	_journey.ALL = field.NewAsterisk(tableName)
	_journey.ID = field.NewInt64(tableName, "id")
	_journey.CreatedAt = field.NewTime(tableName, "created_at")
	_journey.UpdatedAt = field.NewTime(tableName, "updated_at")
	_journey.DeletedAt = field.NewField(tableName, "deleted_at")
	_journey.UserID = field.NewInt64(tableName, "user_id")
	_journey.Title = field.NewString(tableName, "title")
	_journey.Note = field.NewString(tableName, "note")
	_journey.ExpectedReturnTime = field.NewTime(tableName, "expected_return_time")
	_journey.ActualReturnTime = field.NewTime(tableName, "actual_return_time")
	_journey.Status = field.NewString(tableName, "status")
	_journey.ReminderSentAt = field.NewTime(tableName, "reminder_sent_at")
	_journey.AlertTriggeredAt = field.NewTime(tableName, "alert_triggered_at")
	_journey.AlertStatus = field.NewString(tableName, "alert_status")
	_journey.AlertAttempts = field.NewInt64(tableName, "alert_attempts")
	_journey.AlertLastAttemptAt = field.NewTime(tableName, "alert_last_attempt_at")

	_journey.fillFieldMap()

	return _journey
}

type journey struct {
	journeyDo

	ALL                field.Asterisk
	ID                 field.Int64
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field
	UserID             field.Int64
	Title              field.String
	Note               field.String
	ExpectedReturnTime field.Time
	ActualReturnTime   field.Time
	Status             field.String
	ReminderSentAt     field.Time
	AlertTriggeredAt   field.Time
	AlertStatus        field.String
	AlertAttempts      field.Int64
	AlertLastAttemptAt field.Time

	fieldMap map[string]field.Expr
}

func (j journey) Table(newTableName string) *journey {
	j.journeyDo.UseTable(newTableName)
	return j.updateTableName(newTableName)
}

func (j journey) As(alias string) *journey {
	j.journeyDo.DO = *(j.journeyDo.As(alias).(*gen.DO))
	return j.updateTableName(alias)
}

func (j *journey) updateTableName(table string) *journey {
	j.ALL = field.NewAsterisk(table)
	j.ID = field.NewInt64(table, "id")
	j.CreatedAt = field.NewTime(table, "created_at")
	j.UpdatedAt = field.NewTime(table, "updated_at")
	j.DeletedAt = field.NewField(table, "deleted_at")
	j.UserID = field.NewInt64(table, "user_id")
	j.Title = field.NewString(table, "title")
	j.Note = field.NewString(table, "note")
	j.ExpectedReturnTime = field.NewTime(table, "expected_return_time")
	j.ActualReturnTime = field.NewTime(table, "actual_return_time")
	j.Status = field.NewString(table, "status")
	j.ReminderSentAt = field.NewTime(table, "reminder_sent_at")
	j.AlertTriggeredAt = field.NewTime(table, "alert_triggered_at")
	j.AlertStatus = field.NewString(table, "alert_status")
	j.AlertAttempts = field.NewInt64(table, "alert_attempts")
	j.AlertLastAttemptAt = field.NewTime(table, "alert_last_attempt_at")

	j.fillFieldMap()

	return j
}

func (j *journey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := j.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (j *journey) fillFieldMap() {
	j.fieldMap = make(map[string]field.Expr, 15)
	j.fieldMap["id"] = j.ID
	j.fieldMap["created_at"] = j.CreatedAt
	j.fieldMap["updated_at"] = j.UpdatedAt
	j.fieldMap["deleted_at"] = j.DeletedAt
	j.fieldMap["user_id"] = j.UserID
	j.fieldMap["title"] = j.Title
	j.fieldMap["note"] = j.Note
	j.fieldMap["expected_return_time"] = j.ExpectedReturnTime
	j.fieldMap["actual_return_time"] = j.ActualReturnTime
	j.fieldMap["status"] = j.Status
	j.fieldMap["reminder_sent_at"] = j.ReminderSentAt
	j.fieldMap["alert_triggered_at"] = j.AlertTriggeredAt
	j.fieldMap["alert_status"] = j.AlertStatus
	j.fieldMap["alert_attempts"] = j.AlertAttempts
	j.fieldMap["alert_last_attempt_at"] = j.AlertLastAttemptAt
}

func (j journey) clone(db *gorm.DB) journey {
	j.journeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return j
}

func (j journey) replaceDB(db *gorm.DB) journey {
	j.journeyDo.ReplaceDB(db)
	return j
}

type journeyDo struct{ gen.DO }

type IJourneyDo interface {
	gen.SubQuery
	Debug() IJourneyDo
	WithContext(ctx context.Context) IJourneyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IJourneyDo
	WriteDB() IJourneyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IJourneyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IJourneyDo
	Not(conds ...gen.Condition) IJourneyDo
	Or(conds ...gen.Condition) IJourneyDo
	Select(conds ...field.Expr) IJourneyDo
	Where(conds ...gen.Condition) IJourneyDo
	Order(conds ...field.Expr) IJourneyDo
	Distinct(cols ...field.Expr) IJourneyDo
	Omit(cols ...field.Expr) IJourneyDo
	Join(table schema.Tabler, on ...field.Expr) IJourneyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IJourneyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IJourneyDo
	Group(cols ...field.Expr) IJourneyDo
	Having(conds ...gen.Condition) IJourneyDo
	Limit(limit int) IJourneyDo
	Offset(offset int) IJourneyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IJourneyDo
	Unscoped() IJourneyDo
	Create(values ...*model.Journey) error
	CreateInBatches(values []*model.Journey, batchSize int) error
	Save(values ...*model.Journey) error
	First() (*model.Journey, error)
	Take() (*model.Journey, error)
	Last() (*model.Journey, error)
	Find() ([]*model.Journey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Journey, err error)
	FindInBatches(result *[]*model.Journey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Journey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IJourneyDo
	Assign(attrs ...field.AssignExpr) IJourneyDo
	Joins(fields ...field.RelationField) IJourneyDo
	Preload(fields ...field.RelationField) IJourneyDo
	FirstOrInit() (*model.Journey, error)
	FirstOrCreate() (*model.Journey, error)
	FindByPage(offset int, limit int) (result []*model.Journey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IJourneyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	ListByUserIDAndStatus(userID int64, status string, limit int, offset int) (result []*model.Journey, err error)
	ListOngoingJourneys() (result []*model.Journey, err error)
	ListTimeoutJourneys() (result []*model.Journey, err error)
}

// ListByUserIDAndStatus 按用户和状态查询行程（分页）
// SELECT * FROM @@table
// WHERE user_id = @userID
//
//	{{if status != ""}}
//	AND status = @status
//	{{end}}
//
// ORDER BY created_at DESC
// LIMIT @limit OFFSET @offset
func (j journeyDo) ListByUserIDAndStatus(userID int64, status string, limit int, offset int) (result []*model.Journey, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("按用户和状态查询行程（分页） SELECT * FROM journeys WHERE user_id = ? ")
	if status != "" {
		params = append(params, status)
		generateSQL.WriteString("AND status = ? ")
	}
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("ORDER BY created_at DESC LIMIT ? OFFSET ? ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetOngoingJourneys 查询进行中的行程（用于定时任务）
// SELECT * FROM @@table
// WHERE status = 'ongoing'
//
//	AND expected_return_time < NOW()
func (j journeyDo) ListOngoingJourneys() (result []*model.Journey, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("GetOngoingJourneys 查询进行中的行程（用于定时任务） SELECT * FROM journeys WHERE status = 'ongoing' AND expected_return_time < NOW() ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListTimeoutJourneys 查询超时的行程（用于定时任务）
// SELECT * FROM @@table
// WHERE status = 'ongoing'
//
//	AND expected_return_time < NOW() - INTERVAL '10 minutes'
func (j journeyDo) ListTimeoutJourneys() (result []*model.Journey, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("查询超时的行程（用于定时任务） SELECT * FROM journeys WHERE status = 'ongoing' AND expected_return_time < NOW() - INTERVAL '10 minutes' ")

	var executeSQL *gorm.DB
	executeSQL = j.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (j journeyDo) Debug() IJourneyDo {
	return j.withDO(j.DO.Debug())
}

func (j journeyDo) WithContext(ctx context.Context) IJourneyDo {
	return j.withDO(j.DO.WithContext(ctx))
}

func (j journeyDo) ReadDB() IJourneyDo {
	return j.Clauses(dbresolver.Read)
}

func (j journeyDo) WriteDB() IJourneyDo {
	return j.Clauses(dbresolver.Write)
}

func (j journeyDo) Session(config *gorm.Session) IJourneyDo {
	return j.withDO(j.DO.Session(config))
}

func (j journeyDo) Clauses(conds ...clause.Expression) IJourneyDo {
	return j.withDO(j.DO.Clauses(conds...))
}

func (j journeyDo) Returning(value interface{}, columns ...string) IJourneyDo {
	return j.withDO(j.DO.Returning(value, columns...))
}

func (j journeyDo) Not(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Not(conds...))
}

func (j journeyDo) Or(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Or(conds...))
}

func (j journeyDo) Select(conds ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Select(conds...))
}

func (j journeyDo) Where(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Where(conds...))
}

func (j journeyDo) Order(conds ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Order(conds...))
}

func (j journeyDo) Distinct(cols ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Distinct(cols...))
}

func (j journeyDo) Omit(cols ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Omit(cols...))
}

func (j journeyDo) Join(table schema.Tabler, on ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Join(table, on...))
}

func (j journeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.LeftJoin(table, on...))
}

func (j journeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.RightJoin(table, on...))
}

func (j journeyDo) Group(cols ...field.Expr) IJourneyDo {
	return j.withDO(j.DO.Group(cols...))
}

func (j journeyDo) Having(conds ...gen.Condition) IJourneyDo {
	return j.withDO(j.DO.Having(conds...))
}

func (j journeyDo) Limit(limit int) IJourneyDo {
	return j.withDO(j.DO.Limit(limit))
}

func (j journeyDo) Offset(offset int) IJourneyDo {
	return j.withDO(j.DO.Offset(offset))
}

func (j journeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IJourneyDo {
	return j.withDO(j.DO.Scopes(funcs...))
}

func (j journeyDo) Unscoped() IJourneyDo {
	return j.withDO(j.DO.Unscoped())
}

func (j journeyDo) Create(values ...*model.Journey) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Create(values)
}

func (j journeyDo) CreateInBatches(values []*model.Journey, batchSize int) error {
	return j.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (j journeyDo) Save(values ...*model.Journey) error {
	if len(values) == 0 {
		return nil
	}
	return j.DO.Save(values)
}

func (j journeyDo) First() (*model.Journey, error) {
	if result, err := j.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) Take() (*model.Journey, error) {
	if result, err := j.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) Last() (*model.Journey, error) {
	if result, err := j.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) Find() ([]*model.Journey, error) {
	result, err := j.DO.Find()
	return result.([]*model.Journey), err
}

func (j journeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Journey, err error) {
	buf := make([]*model.Journey, 0, batchSize)
	err = j.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (j journeyDo) FindInBatches(result *[]*model.Journey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return j.DO.FindInBatches(result, batchSize, fc)
}

func (j journeyDo) Attrs(attrs ...field.AssignExpr) IJourneyDo {
	return j.withDO(j.DO.Attrs(attrs...))
}

func (j journeyDo) Assign(attrs ...field.AssignExpr) IJourneyDo {
	return j.withDO(j.DO.Assign(attrs...))
}

func (j journeyDo) Joins(fields ...field.RelationField) IJourneyDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Joins(_f))
	}
	return &j
}

func (j journeyDo) Preload(fields ...field.RelationField) IJourneyDo {
	for _, _f := range fields {
		j = *j.withDO(j.DO.Preload(_f))
	}
	return &j
}

func (j journeyDo) FirstOrInit() (*model.Journey, error) {
	if result, err := j.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) FirstOrCreate() (*model.Journey, error) {
	if result, err := j.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Journey), nil
	}
}

func (j journeyDo) FindByPage(offset int, limit int) (result []*model.Journey, count int64, err error) {
	result, err = j.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = j.Offset(-1).Limit(-1).Count()
	return
}

func (j journeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = j.Count()
	if err != nil {
		return
	}

	err = j.Offset(offset).Limit(limit).Scan(result)
	return
}

func (j journeyDo) Scan(result interface{}) (err error) {
	return j.DO.Scan(result)
}

func (j journeyDo) Delete(models ...*model.Journey) (result gen.ResultInfo, err error) {
	return j.DO.Delete(models)
}

func (j *journeyDo) withDO(do gen.Dao) *journeyDo {
	j.DO = *do.(*gen.DO)
	return j
}
