// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"AreYouOK/internal/model"
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNotificationTask(db *gorm.DB, opts ...gen.DOOption) notificationTask {
	_notificationTask := notificationTask{}

	_notificationTask.notificationTaskDo.UseDB(db, opts...)
	_notificationTask.notificationTaskDo.UseModel(&model.NotificationTask{})

	tableName := _notificationTask.notificationTaskDo.TableName()
	_notificationTask.ALL = field.NewAsterisk(tableName)
	_notificationTask.ScheduledAt = field.NewTime(tableName, "scheduled_at")
	_notificationTask.ProcessedAt = field.NewTime(tableName, "processed_at")
	_notificationTask.ContactPriority = field.NewInt(tableName, "contact_priority")
	_notificationTask.ContactPhoneHash = field.NewString(tableName, "contact_phone_hash")
	_notificationTask.Payload = field.NewField(tableName, "payload")
	_notificationTask.CreatedAt = field.NewTime(tableName, "created_at")
	_notificationTask.UpdatedAt = field.NewTime(tableName, "updated_at")
	_notificationTask.DeletedAt = field.NewField(tableName, "deleted_at")
	_notificationTask.ID = field.NewInt64(tableName, "id")
	_notificationTask.Channel = field.NewString(tableName, "channel")
	_notificationTask.Category = field.NewString(tableName, "category")
	_notificationTask.Status = field.NewString(tableName, "status")
	_notificationTask.RetryCount = field.NewInt(tableName, "retry_count")
	_notificationTask.UserID = field.NewInt64(tableName, "user_id")
	_notificationTask.TaskCode = field.NewInt64(tableName, "task_code")
	_notificationTask.CostCents = field.NewInt(tableName, "cost_cents")
	_notificationTask.Deducted = field.NewBool(tableName, "deducted")

	_notificationTask.fillFieldMap()

	return _notificationTask
}

type notificationTask struct {
	notificationTaskDo

	ALL              field.Asterisk
	ScheduledAt      field.Time
	ProcessedAt      field.Time
	ContactPriority  field.Int
	ContactPhoneHash field.String
	Payload          field.Field
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	ID               field.Int64
	Channel          field.String
	Category         field.String
	Status           field.String
	RetryCount       field.Int
	UserID           field.Int64
	TaskCode         field.Int64
	CostCents        field.Int
	Deducted         field.Bool

	fieldMap map[string]field.Expr
}

func (n notificationTask) Table(newTableName string) *notificationTask {
	n.notificationTaskDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n notificationTask) As(alias string) *notificationTask {
	n.notificationTaskDo.DO = *(n.notificationTaskDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *notificationTask) updateTableName(table string) *notificationTask {
	n.ALL = field.NewAsterisk(table)
	n.ScheduledAt = field.NewTime(table, "scheduled_at")
	n.ProcessedAt = field.NewTime(table, "processed_at")
	n.ContactPriority = field.NewInt(table, "contact_priority")
	n.ContactPhoneHash = field.NewString(table, "contact_phone_hash")
	n.Payload = field.NewField(table, "payload")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.DeletedAt = field.NewField(table, "deleted_at")
	n.ID = field.NewInt64(table, "id")
	n.Channel = field.NewString(table, "channel")
	n.Category = field.NewString(table, "category")
	n.Status = field.NewString(table, "status")
	n.RetryCount = field.NewInt(table, "retry_count")
	n.UserID = field.NewInt64(table, "user_id")
	n.TaskCode = field.NewInt64(table, "task_code")
	n.CostCents = field.NewInt(table, "cost_cents")
	n.Deducted = field.NewBool(table, "deducted")

	n.fillFieldMap()

	return n
}

func (n *notificationTask) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *notificationTask) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 17)
	n.fieldMap["scheduled_at"] = n.ScheduledAt
	n.fieldMap["processed_at"] = n.ProcessedAt
	n.fieldMap["contact_priority"] = n.ContactPriority
	n.fieldMap["contact_phone_hash"] = n.ContactPhoneHash
	n.fieldMap["payload"] = n.Payload
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["deleted_at"] = n.DeletedAt
	n.fieldMap["id"] = n.ID
	n.fieldMap["channel"] = n.Channel
	n.fieldMap["category"] = n.Category
	n.fieldMap["status"] = n.Status
	n.fieldMap["retry_count"] = n.RetryCount
	n.fieldMap["user_id"] = n.UserID
	n.fieldMap["task_code"] = n.TaskCode
	n.fieldMap["cost_cents"] = n.CostCents
	n.fieldMap["deducted"] = n.Deducted
}

func (n notificationTask) clone(db *gorm.DB) notificationTask {
	n.notificationTaskDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n notificationTask) replaceDB(db *gorm.DB) notificationTask {
	n.notificationTaskDo.ReplaceDB(db)
	return n
}

type notificationTaskDo struct{ gen.DO }

type INotificationTaskDo interface {
	gen.SubQuery
	Debug() INotificationTaskDo
	WithContext(ctx context.Context) INotificationTaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INotificationTaskDo
	WriteDB() INotificationTaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INotificationTaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INotificationTaskDo
	Not(conds ...gen.Condition) INotificationTaskDo
	Or(conds ...gen.Condition) INotificationTaskDo
	Select(conds ...field.Expr) INotificationTaskDo
	Where(conds ...gen.Condition) INotificationTaskDo
	Order(conds ...field.Expr) INotificationTaskDo
	Distinct(cols ...field.Expr) INotificationTaskDo
	Omit(cols ...field.Expr) INotificationTaskDo
	Join(table schema.Tabler, on ...field.Expr) INotificationTaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INotificationTaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) INotificationTaskDo
	Group(cols ...field.Expr) INotificationTaskDo
	Having(conds ...gen.Condition) INotificationTaskDo
	Limit(limit int) INotificationTaskDo
	Offset(offset int) INotificationTaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationTaskDo
	Unscoped() INotificationTaskDo
	Create(values ...*model.NotificationTask) error
	CreateInBatches(values []*model.NotificationTask, batchSize int) error
	Save(values ...*model.NotificationTask) error
	First() (*model.NotificationTask, error)
	Take() (*model.NotificationTask, error)
	Last() (*model.NotificationTask, error)
	Find() ([]*model.NotificationTask, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationTask, err error)
	FindInBatches(result *[]*model.NotificationTask, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NotificationTask) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INotificationTaskDo
	Assign(attrs ...field.AssignExpr) INotificationTaskDo
	Joins(fields ...field.RelationField) INotificationTaskDo
	Preload(fields ...field.RelationField) INotificationTaskDo
	FirstOrInit() (*model.NotificationTask, error)
	FirstOrCreate() (*model.NotificationTask, error)
	FindByPage(offset int, limit int) (result []*model.NotificationTask, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INotificationTaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByID(id int64) (result *model.NotificationTask, err error)
	GetByTaskCode(taskCode int64) (result *model.NotificationTask, err error)
	GetByPublicIDAndTaskID(publicID int64, taskID int64) (result *model.NotificationTask, err error)
	ListByUserID(userID int64, category string, channel string, status string, limit int, offset int) (result []*model.NotificationTask, err error)
	ListByPublicID(publicID int64, category string, channel string, status string, cursorID int64, limit int) (result []*model.NotificationTask, err error)
	ListPendingTasks(limit int) (result []*model.NotificationTask, err error)
	ListFailedTasksForRetry(limit int) (result []*model.NotificationTask, err error)
	GetWithAttempts(taskID int64) (result map[string]interface{}, err error)
	CountByUserIDAndStatus(userID int64) (result []map[string]interface{}, err error)
}

// GetByID 根据数据库主键 ID 查询通知任务
//
// SELECT * FROM @@table WHERE id = @id LIMIT 1
func (n notificationTaskDo) GetByID(id int64) (result *model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM notification_tasks WHERE id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByTaskCode 根据 TaskCode 查询通知任务（幂等性检查）
//
// SELECT * FROM @@table WHERE task_code = @taskCode LIMIT 1
func (n notificationTaskDo) GetByTaskCode(taskCode int64) (result *model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, taskCode)
	generateSQL.WriteString("SELECT * FROM notification_tasks WHERE task_code = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByPublicIDAndTaskID 根据 PublicID 和 Task ID 查询通知任务（API 常用）
//
// SELECT nt.* FROM @@table nt
// INNER JOIN users u ON u.id = nt.user_id
// WHERE u.public_id = @publicID AND nt.id = @taskID
// LIMIT 1
func (n notificationTaskDo) GetByPublicIDAndTaskID(publicID int64, taskID int64) (result *model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	params = append(params, taskID)
	generateSQL.WriteString("SELECT nt.* FROM notification_tasks nt INNER JOIN users u ON u.id = nt.user_id WHERE u.public_id = ? AND nt.id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByUserID 按用户查询通知任务（分页，支持筛选）
//
// SELECT * FROM @@table
// WHERE user_id = @userID
//
//	{{if category != ""}}
//	AND category = @category
//	{{end}}
//	{{if channel != ""}}
//	AND channel = @channel
//	{{end}}
//	{{if status != ""}}
//	AND status = @status
//	{{end}}
//
// ORDER BY created_at DESC
// LIMIT @limit OFFSET @offset
func (n notificationTaskDo) ListByUserID(userID int64, category string, channel string, status string, limit int, offset int) (result []*model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT * FROM notification_tasks WHERE user_id = ? ")
	if category != "" {
		params = append(params, category)
		generateSQL.WriteString("AND category = ? ")
	}
	if channel != "" {
		params = append(params, channel)
		generateSQL.WriteString("AND channel = ? ")
	}
	if status != "" {
		params = append(params, status)
		generateSQL.WriteString("AND status = ? ")
	}
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("ORDER BY created_at DESC LIMIT ? OFFSET ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByPublicID 根据 PublicID 查询通知任务（API 常用，支持游标分页）
//
// SELECT nt.* FROM @@table nt
// INNER JOIN users u ON u.id = nt.user_id
// WHERE u.public_id = @publicID
//
//	{{if category != ""}}
//	AND nt.category = @category
//	{{end}}
//	{{if channel != ""}}
//	AND nt.channel = @channel
//	{{end}}
//	{{if status != ""}}
//	AND nt.status = @status
//	{{end}}
//	{{if cursorID > 0}}
//	AND nt.id < @cursorID
//	{{end}}
//
// ORDER BY nt.created_at DESC
// LIMIT @limit
func (n notificationTaskDo) ListByPublicID(publicID int64, category string, channel string, status string, cursorID int64, limit int) (result []*model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	generateSQL.WriteString("SELECT nt.* FROM notification_tasks nt INNER JOIN users u ON u.id = nt.user_id WHERE u.public_id = ? ")
	if category != "" {
		params = append(params, category)
		generateSQL.WriteString("AND nt.category = ? ")
	}
	if channel != "" {
		params = append(params, channel)
		generateSQL.WriteString("AND nt.channel = ? ")
	}
	if status != "" {
		params = append(params, status)
		generateSQL.WriteString("AND nt.status = ? ")
	}
	if cursorID > 0 {
		params = append(params, cursorID)
		generateSQL.WriteString("AND nt.id < ? ")
	}
	params = append(params, limit)
	generateSQL.WriteString("ORDER BY nt.created_at DESC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListPendingTasks 查询待处理的任务（用于消息消费）
//
// SELECT * FROM @@table
// WHERE status = 'pending'
//
//	AND scheduled_at <= NOW()
//
// ORDER BY scheduled_at ASC
// LIMIT @limit
func (n notificationTaskDo) ListPendingTasks(limit int) (result []*model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, limit)
	generateSQL.WriteString("SELECT * FROM notification_tasks WHERE status = 'pending' AND scheduled_at <= NOW() ORDER BY scheduled_at ASC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListFailedTasksForRetry 查询失败需要重试的任务
//
// SELECT * FROM @@table
// WHERE status = 'failed'
//
//	AND retry_count < 3
//	AND scheduled_at <= NOW()
//
// ORDER BY scheduled_at ASC
// LIMIT @limit
func (n notificationTaskDo) ListFailedTasksForRetry(limit int) (result []*model.NotificationTask, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, limit)
	generateSQL.WriteString("SELECT * FROM notification_tasks WHERE status = 'failed' AND retry_count < 3 AND scheduled_at <= NOW() ORDER BY scheduled_at ASC LIMIT ? ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetWithAttempts 获取任务及尝试记录（JOIN contact_attempts）
//
// SELECT t.*,
//
//	json_agg(
//	  json_build_object(
//	    'id', ca.id,
//	    'contact_priority', ca.contact_priority,
//	    'contact_phone_hash', ca.contact_phone_hash,
//	    'channel', ca.channel,
//	    'status', ca.status,
//	    'response_code', ca.response_code,
//	    'response_message', ca.response_message,
//	    'cost_cents', ca.cost_cents,
//	    'deducted', ca.deducted,
//	    'attempted_at', ca.attempted_at
//	  ) ORDER BY ca.attempted_at DESC
//	) FILTER (WHERE ca.id IS NOT NULL) as attempts
//
// FROM @@table t
// LEFT JOIN contact_attempts ca ON ca.task_id = t.id
// WHERE t.id = @taskID
// GROUP BY t.id
// LIMIT 1
func (n notificationTaskDo) GetWithAttempts(taskID int64) (result map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, taskID)
	generateSQL.WriteString("SELECT t.*, json_agg( json_build_object( 'id', ca.id, 'contact_priority', ca.contact_priority, 'contact_phone_hash', ca.contact_phone_hash, 'channel', ca.channel, 'status', ca.status, 'response_code', ca.response_code, 'response_message', ca.response_message, 'cost_cents', ca.cost_cents, 'deducted', ca.deducted, 'attempted_at', ca.attempted_at ) ORDER BY ca.attempted_at DESC ) FILTER (WHERE ca.id IS NOT NULL) as attempts FROM notification_tasks t LEFT JOIN contact_attempts ca ON ca.task_id = t.id WHERE t.id = ? GROUP BY t.id LIMIT 1 ")

	result = make(map[string]interface{})
	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Take(result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountByUserIDAndStatus 统计用户通知任务数量（按状态）
//
// SELECT status, COUNT(*) as count
// FROM @@table
// WHERE user_id = @userID
// GROUP BY status
func (n notificationTaskDo) CountByUserIDAndStatus(userID int64) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT status, COUNT(*) as count FROM notification_tasks WHERE user_id = ? GROUP BY status ")

	var executeSQL *gorm.DB
	executeSQL = n.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (n notificationTaskDo) Debug() INotificationTaskDo {
	return n.withDO(n.DO.Debug())
}

func (n notificationTaskDo) WithContext(ctx context.Context) INotificationTaskDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n notificationTaskDo) ReadDB() INotificationTaskDo {
	return n.Clauses(dbresolver.Read)
}

func (n notificationTaskDo) WriteDB() INotificationTaskDo {
	return n.Clauses(dbresolver.Write)
}

func (n notificationTaskDo) Session(config *gorm.Session) INotificationTaskDo {
	return n.withDO(n.DO.Session(config))
}

func (n notificationTaskDo) Clauses(conds ...clause.Expression) INotificationTaskDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n notificationTaskDo) Returning(value interface{}, columns ...string) INotificationTaskDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n notificationTaskDo) Not(conds ...gen.Condition) INotificationTaskDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n notificationTaskDo) Or(conds ...gen.Condition) INotificationTaskDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n notificationTaskDo) Select(conds ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n notificationTaskDo) Where(conds ...gen.Condition) INotificationTaskDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n notificationTaskDo) Order(conds ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n notificationTaskDo) Distinct(cols ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n notificationTaskDo) Omit(cols ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n notificationTaskDo) Join(table schema.Tabler, on ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n notificationTaskDo) LeftJoin(table schema.Tabler, on ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n notificationTaskDo) RightJoin(table schema.Tabler, on ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n notificationTaskDo) Group(cols ...field.Expr) INotificationTaskDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n notificationTaskDo) Having(conds ...gen.Condition) INotificationTaskDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n notificationTaskDo) Limit(limit int) INotificationTaskDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n notificationTaskDo) Offset(offset int) INotificationTaskDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n notificationTaskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INotificationTaskDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n notificationTaskDo) Unscoped() INotificationTaskDo {
	return n.withDO(n.DO.Unscoped())
}

func (n notificationTaskDo) Create(values ...*model.NotificationTask) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n notificationTaskDo) CreateInBatches(values []*model.NotificationTask, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n notificationTaskDo) Save(values ...*model.NotificationTask) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n notificationTaskDo) First() (*model.NotificationTask, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationTask), nil
	}
}

func (n notificationTaskDo) Take() (*model.NotificationTask, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationTask), nil
	}
}

func (n notificationTaskDo) Last() (*model.NotificationTask, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationTask), nil
	}
}

func (n notificationTaskDo) Find() ([]*model.NotificationTask, error) {
	result, err := n.DO.Find()
	return result.([]*model.NotificationTask), err
}

func (n notificationTaskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NotificationTask, err error) {
	buf := make([]*model.NotificationTask, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n notificationTaskDo) FindInBatches(result *[]*model.NotificationTask, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n notificationTaskDo) Attrs(attrs ...field.AssignExpr) INotificationTaskDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n notificationTaskDo) Assign(attrs ...field.AssignExpr) INotificationTaskDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n notificationTaskDo) Joins(fields ...field.RelationField) INotificationTaskDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n notificationTaskDo) Preload(fields ...field.RelationField) INotificationTaskDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n notificationTaskDo) FirstOrInit() (*model.NotificationTask, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationTask), nil
	}
}

func (n notificationTaskDo) FirstOrCreate() (*model.NotificationTask, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NotificationTask), nil
	}
}

func (n notificationTaskDo) FindByPage(offset int, limit int) (result []*model.NotificationTask, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n notificationTaskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n notificationTaskDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n notificationTaskDo) Delete(models ...*model.NotificationTask) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *notificationTaskDo) withDO(do gen.Dao) *notificationTaskDo {
	n.DO = *do.(*gen.DO)
	return n
}
