// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"AreYouOK/internal/model"
)

func newQuotaTransaction(db *gorm.DB, opts ...gen.DOOption) quotaTransaction {
	_quotaTransaction := quotaTransaction{}

	_quotaTransaction.quotaTransactionDo.UseDB(db, opts...)
	_quotaTransaction.quotaTransactionDo.UseModel(&model.QuotaTransaction{})

	tableName := _quotaTransaction.quotaTransactionDo.TableName()
	_quotaTransaction.ALL = field.NewAsterisk(tableName)
	_quotaTransaction.ID = field.NewInt64(tableName, "id")
	_quotaTransaction.CreatedAt = field.NewTime(tableName, "created_at")
	_quotaTransaction.UpdatedAt = field.NewTime(tableName, "updated_at")
	_quotaTransaction.DeletedAt = field.NewField(tableName, "deleted_at")
	_quotaTransaction.UserID = field.NewInt64(tableName, "user_id")
	_quotaTransaction.Channel = field.NewString(tableName, "channel")
	_quotaTransaction.TransactionType = field.NewString(tableName, "transaction_type")
	_quotaTransaction.Reason = field.NewString(tableName, "reason")
	_quotaTransaction.Amount = field.NewInt64(tableName, "amount")
	_quotaTransaction.BalanceAfter = field.NewInt64(tableName, "balance_after")

	_quotaTransaction.fillFieldMap()

	return _quotaTransaction
}

type quotaTransaction struct {
	quotaTransactionDo

	ALL             field.Asterisk
	ID              field.Int64
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Field
	UserID          field.Int64
	Channel         field.String
	TransactionType field.String
	Reason          field.String
	Amount          field.Int64
	BalanceAfter    field.Int64

	fieldMap map[string]field.Expr
}

func (q quotaTransaction) Table(newTableName string) *quotaTransaction {
	q.quotaTransactionDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quotaTransaction) As(alias string) *quotaTransaction {
	q.quotaTransactionDo.DO = *(q.quotaTransactionDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quotaTransaction) updateTableName(table string) *quotaTransaction {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt64(table, "id")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.UpdatedAt = field.NewTime(table, "updated_at")
	q.DeletedAt = field.NewField(table, "deleted_at")
	q.UserID = field.NewInt64(table, "user_id")
	q.Channel = field.NewString(table, "channel")
	q.TransactionType = field.NewString(table, "transaction_type")
	q.Reason = field.NewString(table, "reason")
	q.Amount = field.NewInt64(table, "amount")
	q.BalanceAfter = field.NewInt64(table, "balance_after")

	q.fillFieldMap()

	return q
}

func (q *quotaTransaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quotaTransaction) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 10)
	q.fieldMap["id"] = q.ID
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.UpdatedAt
	q.fieldMap["deleted_at"] = q.DeletedAt
	q.fieldMap["user_id"] = q.UserID
	q.fieldMap["channel"] = q.Channel
	q.fieldMap["transaction_type"] = q.TransactionType
	q.fieldMap["reason"] = q.Reason
	q.fieldMap["amount"] = q.Amount
	q.fieldMap["balance_after"] = q.BalanceAfter
}

func (q quotaTransaction) clone(db *gorm.DB) quotaTransaction {
	q.quotaTransactionDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quotaTransaction) replaceDB(db *gorm.DB) quotaTransaction {
	q.quotaTransactionDo.ReplaceDB(db)
	return q
}

type quotaTransactionDo struct{ gen.DO }

type IQuotaTransactionDo interface {
	gen.SubQuery
	Debug() IQuotaTransactionDo
	WithContext(ctx context.Context) IQuotaTransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuotaTransactionDo
	WriteDB() IQuotaTransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuotaTransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuotaTransactionDo
	Not(conds ...gen.Condition) IQuotaTransactionDo
	Or(conds ...gen.Condition) IQuotaTransactionDo
	Select(conds ...field.Expr) IQuotaTransactionDo
	Where(conds ...gen.Condition) IQuotaTransactionDo
	Order(conds ...field.Expr) IQuotaTransactionDo
	Distinct(cols ...field.Expr) IQuotaTransactionDo
	Omit(cols ...field.Expr) IQuotaTransactionDo
	Join(table schema.Tabler, on ...field.Expr) IQuotaTransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuotaTransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuotaTransactionDo
	Group(cols ...field.Expr) IQuotaTransactionDo
	Having(conds ...gen.Condition) IQuotaTransactionDo
	Limit(limit int) IQuotaTransactionDo
	Offset(offset int) IQuotaTransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuotaTransactionDo
	Unscoped() IQuotaTransactionDo
	Create(values ...*model.QuotaTransaction) error
	CreateInBatches(values []*model.QuotaTransaction, batchSize int) error
	Save(values ...*model.QuotaTransaction) error
	First() (*model.QuotaTransaction, error)
	Take() (*model.QuotaTransaction, error)
	Last() (*model.QuotaTransaction, error)
	Find() ([]*model.QuotaTransaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuotaTransaction, err error)
	FindInBatches(result *[]*model.QuotaTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.QuotaTransaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuotaTransactionDo
	Assign(attrs ...field.AssignExpr) IQuotaTransactionDo
	Joins(fields ...field.RelationField) IQuotaTransactionDo
	Preload(fields ...field.RelationField) IQuotaTransactionDo
	FirstOrInit() (*model.QuotaTransaction, error)
	FirstOrCreate() (*model.QuotaTransaction, error)
	FindByPage(offset int, limit int) (result []*model.QuotaTransaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuotaTransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetBalanceByUserID(userID int64) (result []map[string]interface{}, err error)
	ListByUserID(userID int64, limit int, offset int) (result []*model.QuotaTransaction, err error)
}

// GetBalanceByUserID 计算用户余额（按渠道分组）
// SELECT
//
//	channel,
//	COALESCE(SUM(CASE WHEN transaction_type = 'grant' THEN amount ELSE 0 END) -
//	         SUM(CASE WHEN transaction_type = 'deduct' THEN amount ELSE 0 END), 0) as balance
//
// FROM @@table
// WHERE user_id = @userID
// GROUP BY channel
func (q quotaTransactionDo) GetBalanceByUserID(userID int64) (result []map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("计算用户余额（按渠道分组） SELECT channel, COALESCE(SUM(CASE WHEN transaction_type = 'grant' THEN amount ELSE 0 END) - SUM(CASE WHEN transaction_type = 'deduct' THEN amount ELSE 0 END), 0) as balance FROM quota_transactions WHERE user_id = ? GROUP BY channel ")

	var executeSQL *gorm.DB
	executeSQL = q.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByUserID 按用户查询流水（分页）
// SELECT * FROM @@table
// WHERE user_id = @userID
// ORDER BY created_at DESC
// LIMIT @limit OFFSET @offset
func (q quotaTransactionDo) ListByUserID(userID int64, limit int, offset int) (result []*model.QuotaTransaction, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	params = append(params, limit)
	params = append(params, offset)
	generateSQL.WriteString("按用户查询流水（分页） SELECT * FROM quota_transactions WHERE user_id = ? ORDER BY created_at DESC LIMIT ? OFFSET ? ")

	var executeSQL *gorm.DB
	executeSQL = q.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (q quotaTransactionDo) Debug() IQuotaTransactionDo {
	return q.withDO(q.DO.Debug())
}

func (q quotaTransactionDo) WithContext(ctx context.Context) IQuotaTransactionDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quotaTransactionDo) ReadDB() IQuotaTransactionDo {
	return q.Clauses(dbresolver.Read)
}

func (q quotaTransactionDo) WriteDB() IQuotaTransactionDo {
	return q.Clauses(dbresolver.Write)
}

func (q quotaTransactionDo) Session(config *gorm.Session) IQuotaTransactionDo {
	return q.withDO(q.DO.Session(config))
}

func (q quotaTransactionDo) Clauses(conds ...clause.Expression) IQuotaTransactionDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quotaTransactionDo) Returning(value interface{}, columns ...string) IQuotaTransactionDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quotaTransactionDo) Not(conds ...gen.Condition) IQuotaTransactionDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quotaTransactionDo) Or(conds ...gen.Condition) IQuotaTransactionDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quotaTransactionDo) Select(conds ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quotaTransactionDo) Where(conds ...gen.Condition) IQuotaTransactionDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quotaTransactionDo) Order(conds ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quotaTransactionDo) Distinct(cols ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quotaTransactionDo) Omit(cols ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quotaTransactionDo) Join(table schema.Tabler, on ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quotaTransactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quotaTransactionDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quotaTransactionDo) Group(cols ...field.Expr) IQuotaTransactionDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quotaTransactionDo) Having(conds ...gen.Condition) IQuotaTransactionDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quotaTransactionDo) Limit(limit int) IQuotaTransactionDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quotaTransactionDo) Offset(offset int) IQuotaTransactionDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quotaTransactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuotaTransactionDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quotaTransactionDo) Unscoped() IQuotaTransactionDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quotaTransactionDo) Create(values ...*model.QuotaTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quotaTransactionDo) CreateInBatches(values []*model.QuotaTransaction, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quotaTransactionDo) Save(values ...*model.QuotaTransaction) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quotaTransactionDo) First() (*model.QuotaTransaction, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaTransaction), nil
	}
}

func (q quotaTransactionDo) Take() (*model.QuotaTransaction, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaTransaction), nil
	}
}

func (q quotaTransactionDo) Last() (*model.QuotaTransaction, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaTransaction), nil
	}
}

func (q quotaTransactionDo) Find() ([]*model.QuotaTransaction, error) {
	result, err := q.DO.Find()
	return result.([]*model.QuotaTransaction), err
}

func (q quotaTransactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuotaTransaction, err error) {
	buf := make([]*model.QuotaTransaction, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quotaTransactionDo) FindInBatches(result *[]*model.QuotaTransaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quotaTransactionDo) Attrs(attrs ...field.AssignExpr) IQuotaTransactionDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quotaTransactionDo) Assign(attrs ...field.AssignExpr) IQuotaTransactionDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quotaTransactionDo) Joins(fields ...field.RelationField) IQuotaTransactionDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quotaTransactionDo) Preload(fields ...field.RelationField) IQuotaTransactionDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quotaTransactionDo) FirstOrInit() (*model.QuotaTransaction, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaTransaction), nil
	}
}

func (q quotaTransactionDo) FirstOrCreate() (*model.QuotaTransaction, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaTransaction), nil
	}
}

func (q quotaTransactionDo) FindByPage(offset int, limit int) (result []*model.QuotaTransaction, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quotaTransactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quotaTransactionDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quotaTransactionDo) Delete(models ...*model.QuotaTransaction) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quotaTransactionDo) withDO(do gen.Dao) *quotaTransactionDo {
	q.DO = *do.(*gen.DO)
	return q
}
