// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"AreYouOK/internal/model"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newQuotaWallet(db *gorm.DB, opts ...gen.DOOption) quotaWallet {
	_quotaWallet := quotaWallet{}

	_quotaWallet.quotaWalletDo.UseDB(db, opts...)
	_quotaWallet.quotaWalletDo.UseModel(&model.QuotaWallet{})

	tableName := _quotaWallet.quotaWalletDo.TableName()
	_quotaWallet.ALL = field.NewAsterisk(tableName)
	_quotaWallet.ID = field.NewInt64(tableName, "id")
	_quotaWallet.UserID = field.NewInt64(tableName, "user_id")
	_quotaWallet.Channel = field.NewString(tableName, "channel")
	_quotaWallet.AvailableAmount = field.NewInt(tableName, "available_amount")
	_quotaWallet.FrozenAmount = field.NewInt(tableName, "frozen_amount")
	_quotaWallet.UsedAmount = field.NewInt(tableName, "used_amount")
	_quotaWallet.TotalGranted = field.NewInt(tableName, "total_granted")
	_quotaWallet.CreatedAt = field.NewTime(tableName, "created_at")
	_quotaWallet.UpdatedAt = field.NewTime(tableName, "updated_at")

	_quotaWallet.fillFieldMap()

	return _quotaWallet
}

type quotaWallet struct {
	quotaWalletDo

	ALL             field.Asterisk
	ID              field.Int64
	UserID          field.Int64
	Channel         field.String
	AvailableAmount field.Int
	FrozenAmount    field.Int
	UsedAmount      field.Int
	TotalGranted    field.Int
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (q quotaWallet) Table(newTableName string) *quotaWallet {
	q.quotaWalletDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q quotaWallet) As(alias string) *quotaWallet {
	q.quotaWalletDo.DO = *(q.quotaWalletDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *quotaWallet) updateTableName(table string) *quotaWallet {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewInt64(table, "id")
	q.UserID = field.NewInt64(table, "user_id")
	q.Channel = field.NewString(table, "channel")
	q.AvailableAmount = field.NewInt(table, "available_amount")
	q.FrozenAmount = field.NewInt(table, "frozen_amount")
	q.UsedAmount = field.NewInt(table, "used_amount")
	q.TotalGranted = field.NewInt(table, "total_granted")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.UpdatedAt = field.NewTime(table, "updated_at")

	q.fillFieldMap()

	return q
}

func (q *quotaWallet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *quotaWallet) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 9)
	q.fieldMap["id"] = q.ID
	q.fieldMap["user_id"] = q.UserID
	q.fieldMap["channel"] = q.Channel
	q.fieldMap["available_amount"] = q.AvailableAmount
	q.fieldMap["frozen_amount"] = q.FrozenAmount
	q.fieldMap["used_amount"] = q.UsedAmount
	q.fieldMap["total_granted"] = q.TotalGranted
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.UpdatedAt
}

func (q quotaWallet) clone(db *gorm.DB) quotaWallet {
	q.quotaWalletDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q quotaWallet) replaceDB(db *gorm.DB) quotaWallet {
	q.quotaWalletDo.ReplaceDB(db)
	return q
}

type quotaWalletDo struct{ gen.DO }

type IQuotaWalletDo interface {
	gen.SubQuery
	Debug() IQuotaWalletDo
	WithContext(ctx context.Context) IQuotaWalletDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuotaWalletDo
	WriteDB() IQuotaWalletDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuotaWalletDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuotaWalletDo
	Not(conds ...gen.Condition) IQuotaWalletDo
	Or(conds ...gen.Condition) IQuotaWalletDo
	Select(conds ...field.Expr) IQuotaWalletDo
	Where(conds ...gen.Condition) IQuotaWalletDo
	Order(conds ...field.Expr) IQuotaWalletDo
	Distinct(cols ...field.Expr) IQuotaWalletDo
	Omit(cols ...field.Expr) IQuotaWalletDo
	Join(table schema.Tabler, on ...field.Expr) IQuotaWalletDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuotaWalletDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuotaWalletDo
	Group(cols ...field.Expr) IQuotaWalletDo
	Having(conds ...gen.Condition) IQuotaWalletDo
	Limit(limit int) IQuotaWalletDo
	Offset(offset int) IQuotaWalletDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuotaWalletDo
	Unscoped() IQuotaWalletDo
	Create(values ...*model.QuotaWallet) error
	CreateInBatches(values []*model.QuotaWallet, batchSize int) error
	Save(values ...*model.QuotaWallet) error
	First() (*model.QuotaWallet, error)
	Take() (*model.QuotaWallet, error)
	Last() (*model.QuotaWallet, error)
	Find() ([]*model.QuotaWallet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuotaWallet, err error)
	FindInBatches(result *[]*model.QuotaWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.QuotaWallet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuotaWalletDo
	Assign(attrs ...field.AssignExpr) IQuotaWalletDo
	Joins(fields ...field.RelationField) IQuotaWalletDo
	Preload(fields ...field.RelationField) IQuotaWalletDo
	FirstOrInit() (*model.QuotaWallet, error)
	FirstOrCreate() (*model.QuotaWallet, error)
	FindByPage(offset int, limit int) (result []*model.QuotaWallet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuotaWalletDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q quotaWalletDo) Debug() IQuotaWalletDo {
	return q.withDO(q.DO.Debug())
}

func (q quotaWalletDo) WithContext(ctx context.Context) IQuotaWalletDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q quotaWalletDo) ReadDB() IQuotaWalletDo {
	return q.Clauses(dbresolver.Read)
}

func (q quotaWalletDo) WriteDB() IQuotaWalletDo {
	return q.Clauses(dbresolver.Write)
}

func (q quotaWalletDo) Session(config *gorm.Session) IQuotaWalletDo {
	return q.withDO(q.DO.Session(config))
}

func (q quotaWalletDo) Clauses(conds ...clause.Expression) IQuotaWalletDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q quotaWalletDo) Returning(value interface{}, columns ...string) IQuotaWalletDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q quotaWalletDo) Not(conds ...gen.Condition) IQuotaWalletDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q quotaWalletDo) Or(conds ...gen.Condition) IQuotaWalletDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q quotaWalletDo) Select(conds ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q quotaWalletDo) Where(conds ...gen.Condition) IQuotaWalletDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q quotaWalletDo) Order(conds ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q quotaWalletDo) Distinct(cols ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q quotaWalletDo) Omit(cols ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q quotaWalletDo) Join(table schema.Tabler, on ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q quotaWalletDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q quotaWalletDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q quotaWalletDo) Group(cols ...field.Expr) IQuotaWalletDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q quotaWalletDo) Having(conds ...gen.Condition) IQuotaWalletDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q quotaWalletDo) Limit(limit int) IQuotaWalletDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q quotaWalletDo) Offset(offset int) IQuotaWalletDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q quotaWalletDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuotaWalletDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q quotaWalletDo) Unscoped() IQuotaWalletDo {
	return q.withDO(q.DO.Unscoped())
}

func (q quotaWalletDo) Create(values ...*model.QuotaWallet) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q quotaWalletDo) CreateInBatches(values []*model.QuotaWallet, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q quotaWalletDo) Save(values ...*model.QuotaWallet) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q quotaWalletDo) First() (*model.QuotaWallet, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaWallet), nil
	}
}

func (q quotaWalletDo) Take() (*model.QuotaWallet, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaWallet), nil
	}
}

func (q quotaWalletDo) Last() (*model.QuotaWallet, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaWallet), nil
	}
}

func (q quotaWalletDo) Find() ([]*model.QuotaWallet, error) {
	result, err := q.DO.Find()
	return result.([]*model.QuotaWallet), err
}

func (q quotaWalletDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QuotaWallet, err error) {
	buf := make([]*model.QuotaWallet, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q quotaWalletDo) FindInBatches(result *[]*model.QuotaWallet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q quotaWalletDo) Attrs(attrs ...field.AssignExpr) IQuotaWalletDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q quotaWalletDo) Assign(attrs ...field.AssignExpr) IQuotaWalletDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q quotaWalletDo) Joins(fields ...field.RelationField) IQuotaWalletDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q quotaWalletDo) Preload(fields ...field.RelationField) IQuotaWalletDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q quotaWalletDo) FirstOrInit() (*model.QuotaWallet, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaWallet), nil
	}
}

func (q quotaWalletDo) FirstOrCreate() (*model.QuotaWallet, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.QuotaWallet), nil
	}
}

func (q quotaWalletDo) FindByPage(offset int, limit int) (result []*model.QuotaWallet, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q quotaWalletDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q quotaWalletDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q quotaWalletDo) Delete(models ...*model.QuotaWallet) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *quotaWalletDo) withDO(do gen.Dao) *quotaWalletDo {
	q.DO = *do.(*gen.DO)
	return q
}
