// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"AreYouOK/internal/model"
	"context"
	"database/sql"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUser(db *gorm.DB, opts ...gen.DOOption) user {
	_user := user{}

	_user.userDo.UseDB(db, opts...)
	_user.userDo.UseModel(&model.User{})

	tableName := _user.userDo.TableName()
	_user.ALL = field.NewAsterisk(tableName)
	_user.DailyCheckInRemindAt = field.NewString(tableName, "daily_check_in_remind_at")
	_user.DailyCheckInGraceUntil = field.NewString(tableName, "daily_check_in_grace_until")
	_user.DailyCheckInDeadline = field.NewString(tableName, "daily_check_in_deadline")
	_user.PhoneHash = field.NewString(tableName, "phone_hash")
	_user.CreatedAt = field.NewTime(tableName, "created_at")
	_user.UpdatedAt = field.NewTime(tableName, "updated_at")
	_user.DeletedAt = field.NewField(tableName, "deleted_at")
	_user.ID = field.NewInt64(tableName, "id")
	_user.Status = field.NewString(tableName, "status")
	_user.Timezone = field.NewString(tableName, "timezone")
	_user.Nickname = field.NewString(tableName, "nickname")
	_user.AlipayOpenID = field.NewString(tableName, "alipay_open_id")
	_user.PhoneCipher = field.NewBytes(tableName, "phone_cipher")
	_user.EmergencyContacts = field.NewField(tableName, "emergency_contacts")
	_user.PublicID = field.NewInt64(tableName, "public_id")
	_user.DailyCheckInEnabled = field.NewBool(tableName, "daily_check_in_enabled")
	_user.JourneyAutoNotify = field.NewBool(tableName, "journey_auto_notify")

	_user.fillFieldMap()

	return _user
}

type user struct {
	userDo

	ALL                    field.Asterisk
	DailyCheckInRemindAt   field.String
	DailyCheckInGraceUntil field.String
	DailyCheckInDeadline   field.String
	PhoneHash              field.String
	CreatedAt              field.Time
	UpdatedAt              field.Time
	DeletedAt              field.Field
	ID                     field.Int64
	Status                 field.String
	Timezone               field.String
	Nickname               field.String
	AlipayOpenID           field.String
	PhoneCipher            field.Bytes
	EmergencyContacts      field.Field
	PublicID               field.Int64
	DailyCheckInEnabled    field.Bool
	JourneyAutoNotify      field.Bool

	fieldMap map[string]field.Expr
}

func (u user) Table(newTableName string) *user {
	u.userDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u user) As(alias string) *user {
	u.userDo.DO = *(u.userDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *user) updateTableName(table string) *user {
	u.ALL = field.NewAsterisk(table)
	u.DailyCheckInRemindAt = field.NewString(table, "daily_check_in_remind_at")
	u.DailyCheckInGraceUntil = field.NewString(table, "daily_check_in_grace_until")
	u.DailyCheckInDeadline = field.NewString(table, "daily_check_in_deadline")
	u.PhoneHash = field.NewString(table, "phone_hash")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")
	u.ID = field.NewInt64(table, "id")
	u.Status = field.NewString(table, "status")
	u.Timezone = field.NewString(table, "timezone")
	u.Nickname = field.NewString(table, "nickname")
	u.AlipayOpenID = field.NewString(table, "alipay_open_id")
	u.PhoneCipher = field.NewBytes(table, "phone_cipher")
	u.EmergencyContacts = field.NewField(table, "emergency_contacts")
	u.PublicID = field.NewInt64(table, "public_id")
	u.DailyCheckInEnabled = field.NewBool(table, "daily_check_in_enabled")
	u.JourneyAutoNotify = field.NewBool(table, "journey_auto_notify")

	u.fillFieldMap()

	return u
}

func (u *user) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *user) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 17)
	u.fieldMap["daily_check_in_remind_at"] = u.DailyCheckInRemindAt
	u.fieldMap["daily_check_in_grace_until"] = u.DailyCheckInGraceUntil
	u.fieldMap["daily_check_in_deadline"] = u.DailyCheckInDeadline
	u.fieldMap["phone_hash"] = u.PhoneHash
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
	u.fieldMap["id"] = u.ID
	u.fieldMap["status"] = u.Status
	u.fieldMap["timezone"] = u.Timezone
	u.fieldMap["nickname"] = u.Nickname
	u.fieldMap["alipay_open_id"] = u.AlipayOpenID
	u.fieldMap["phone_cipher"] = u.PhoneCipher
	u.fieldMap["emergency_contacts"] = u.EmergencyContacts
	u.fieldMap["public_id"] = u.PublicID
	u.fieldMap["daily_check_in_enabled"] = u.DailyCheckInEnabled
	u.fieldMap["journey_auto_notify"] = u.JourneyAutoNotify
}

func (u user) clone(db *gorm.DB) user {
	u.userDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u user) replaceDB(db *gorm.DB) user {
	u.userDo.ReplaceDB(db)
	return u
}

type userDo struct{ gen.DO }

type IUserDo interface {
	gen.SubQuery
	Debug() IUserDo
	WithContext(ctx context.Context) IUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserDo
	WriteDB() IUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserDo
	Not(conds ...gen.Condition) IUserDo
	Or(conds ...gen.Condition) IUserDo
	Select(conds ...field.Expr) IUserDo
	Where(conds ...gen.Condition) IUserDo
	Order(conds ...field.Expr) IUserDo
	Distinct(cols ...field.Expr) IUserDo
	Omit(cols ...field.Expr) IUserDo
	Join(table schema.Tabler, on ...field.Expr) IUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserDo
	Group(cols ...field.Expr) IUserDo
	Having(conds ...gen.Condition) IUserDo
	Limit(limit int) IUserDo
	Offset(offset int) IUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo
	Unscoped() IUserDo
	Create(values ...*model.User) error
	CreateInBatches(values []*model.User, batchSize int) error
	Save(values ...*model.User) error
	First() (*model.User, error)
	Take() (*model.User, error)
	Last() (*model.User, error)
	Find() ([]*model.User, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User, err error)
	FindInBatches(result *[]*model.User, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.User) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserDo
	Assign(attrs ...field.AssignExpr) IUserDo
	Joins(fields ...field.RelationField) IUserDo
	Preload(fields ...field.RelationField) IUserDo
	FirstOrInit() (*model.User, error)
	FirstOrCreate() (*model.User, error)
	FindByPage(offset int, limit int) (result []*model.User, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	GetByAlipayOpenID(openID string) (result *model.User, err error)
	GetByPhoneHash(phoneHash string) (result *model.User, err error)
	GetByPublicID(publicID int64) (result *model.User, err error)
	GetByID(id int64) (result *model.User, err error)
	ListByStatus(status string, limit int, offset int) (result []*model.User, err error)
	ListActiveUsersWithCheckInEnabled() (result []*model.User, err error)
	CountByStatus() (result []map[string]interface{}, err error)
	GetWithQuotas(userID int64) (result map[string]interface{}, err error)
	GetByPublicIDWithQuotas(publicID int64) (result map[string]interface{}, err error)
}

// GetByAlipayOpenID 根据支付宝 OpenID 查询用户
//
// SELECT * FROM @@table WHERE alipay_open_id = @openID LIMIT 1
func (u userDo) GetByAlipayOpenID(openID string) (result *model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, openID)
	generateSQL.WriteString("SELECT * FROM users WHERE alipay_open_id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByPhoneHash 根据手机号哈希查询用户
//
// SELECT * FROM @@table WHERE phone_hash = @phoneHash LIMIT 1
func (u userDo) GetByPhoneHash(phoneHash string) (result *model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, phoneHash)
	generateSQL.WriteString("SELECT * FROM users WHERE phone_hash = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByPublicID 根据 PublicID 查询用户（最常用，API 中 userID 是 public_id）
//
// SELECT * FROM @@table WHERE public_id = @publicID LIMIT 1
func (u userDo) GetByPublicID(publicID int64) (result *model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	generateSQL.WriteString("SELECT * FROM users WHERE public_id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByID 根据数据库主键 ID 查询用户
//
// SELECT * FROM @@table WHERE id = @id LIMIT 1
func (u userDo) GetByID(id int64) (result *model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, id)
	generateSQL.WriteString("SELECT * FROM users WHERE id = ? LIMIT 1 ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListByStatus 根据状态查询用户列表（用于管理后台或定时任务）
//
// SELECT * FROM @@table
// WHERE status = @status
// {{if limit > 0}}
// LIMIT @limit
// {{end}}
// {{if offset > 0}}
// OFFSET @offset
// {{end}}
func (u userDo) ListByStatus(status string, limit int, offset int) (result []*model.User, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, status)
	generateSQL.WriteString("SELECT * FROM users WHERE status = ? ")
	if limit > 0 {
		params = append(params, limit)
		generateSQL.WriteString("LIMIT ? ")
	}
	if offset > 0 {
		params = append(params, offset)
		generateSQL.WriteString("OFFSET ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// ListActiveUsersWithCheckInEnabled 查询开启打卡的活跃用户（用于定时任务）
//
// SELECT * FROM @@table
// WHERE status = 'active'
//
//	AND daily_check_in_enabled = true
func (u userDo) ListActiveUsersWithCheckInEnabled() (result []*model.User, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT * FROM users WHERE status = 'active' AND daily_check_in_enabled = true ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// CountByStatus 统计各状态的用户数量
//
// SELECT status, COUNT(*) as count
// FROM @@table
// GROUP BY status
func (u userDo) CountByStatus() (result []map[string]interface{}, err error) {
	var generateSQL strings.Builder
	generateSQL.WriteString("SELECT status, COUNT(*) as count FROM users GROUP BY status ")

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String()).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetWithQuotas 获取用户及额度信息（JOIN quota_wallets 查询余额）
//
// SELECT u.*,
//
//	COALESCE(qw_sms.available_amount, 0) as sms_balance,
//	COALESCE(qw_voice.available_amount, 0) as voice_balance
//
// FROM @@table u
// LEFT JOIN quota_wallets qw_sms ON qw_sms.user_id = u.id AND qw_sms.channel = 'sms'
// LEFT JOIN quota_wallets qw_voice ON qw_voice.user_id = u.id AND qw_voice.channel = 'voice'
// WHERE u.id = @userID
// LIMIT 1
func (u userDo) GetWithQuotas(userID int64) (result map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, userID)
	generateSQL.WriteString("SELECT u.*, COALESCE(qw_sms.available_amount, 0) as sms_balance, COALESCE(qw_voice.available_amount, 0) as voice_balance FROM users u LEFT JOIN quota_wallets qw_sms ON qw_sms.user_id = u.id AND qw_sms.channel = 'sms' LEFT JOIN quota_wallets qw_voice ON qw_voice.user_id = u.id AND qw_voice.channel = 'voice' WHERE u.id = ? LIMIT 1 ")

	result = make(map[string]interface{})
	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(result) // ignore_security_alert
	err = executeSQL.Error

	return
}

// GetByPublicIDWithQuotas 根据 PublicID 获取用户及额度信息（API 常用）
//
// SELECT u.*,
//
//	COALESCE(qw_sms.available_amount, 0) as sms_balance,
//	COALESCE(qw_voice.available_amount, 0) as voice_balance
//
// FROM @@table u
// LEFT JOIN quota_wallets qw_sms ON qw_sms.user_id = u.id AND qw_sms.channel = 'sms'
// LEFT JOIN quota_wallets qw_voice ON qw_voice.user_id = u.id AND qw_voice.channel = 'voice'
// WHERE u.public_id = @publicID
// LIMIT 1
func (u userDo) GetByPublicIDWithQuotas(publicID int64) (result map[string]interface{}, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, publicID)
	generateSQL.WriteString("SELECT u.*, COALESCE(qw_sms.available_amount, 0) as sms_balance, COALESCE(qw_voice.available_amount, 0) as voice_balance FROM users u LEFT JOIN quota_wallets qw_sms ON qw_sms.user_id = u.id AND qw_sms.channel = 'sms' LEFT JOIN quota_wallets qw_voice ON qw_voice.user_id = u.id AND qw_voice.channel = 'voice' WHERE u.public_id = ? LIMIT 1 ")

	result = make(map[string]interface{})
	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Take(result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (u userDo) Debug() IUserDo {
	return u.withDO(u.DO.Debug())
}

func (u userDo) WithContext(ctx context.Context) IUserDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userDo) ReadDB() IUserDo {
	return u.Clauses(dbresolver.Read)
}

func (u userDo) WriteDB() IUserDo {
	return u.Clauses(dbresolver.Write)
}

func (u userDo) Session(config *gorm.Session) IUserDo {
	return u.withDO(u.DO.Session(config))
}

func (u userDo) Clauses(conds ...clause.Expression) IUserDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userDo) Returning(value interface{}, columns ...string) IUserDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userDo) Not(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userDo) Or(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userDo) Select(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userDo) Where(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userDo) Order(conds ...field.Expr) IUserDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userDo) Distinct(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userDo) Omit(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userDo) Join(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userDo) Group(cols ...field.Expr) IUserDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userDo) Having(conds ...gen.Condition) IUserDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userDo) Limit(limit int) IUserDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userDo) Offset(offset int) IUserDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userDo) Unscoped() IUserDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userDo) Create(values ...*model.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userDo) CreateInBatches(values []*model.User, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userDo) Save(values ...*model.User) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userDo) First() (*model.User, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Take() (*model.User, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Last() (*model.User, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) Find() ([]*model.User, error) {
	result, err := u.DO.Find()
	return result.([]*model.User), err
}

func (u userDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.User, err error) {
	buf := make([]*model.User, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userDo) FindInBatches(result *[]*model.User, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userDo) Attrs(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userDo) Assign(attrs ...field.AssignExpr) IUserDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userDo) Joins(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userDo) Preload(fields ...field.RelationField) IUserDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userDo) FirstOrInit() (*model.User, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) FirstOrCreate() (*model.User, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.User), nil
	}
}

func (u userDo) FindByPage(offset int, limit int) (result []*model.User, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userDo) Delete(models ...*model.User) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userDo) withDO(do gen.Dao) *userDo {
	u.DO = *do.(*gen.DO)
	return u
}
