// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDailyCheckIn = "daily_check_ins"

// DailyCheckIn mapped from table <daily_check_ins>
type DailyCheckIn struct {
	ID               int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	UserID           int64          `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	CheckInDate      time.Time      `gorm:"column:check_in_date;type:date;not null" json:"check_in_date"`
	Status           string         `gorm:"column:status;type:character varying(16);not null;default:pending" json:"status"`
	CheckInAt        *time.Time     `gorm:"column:check_in_at;type:timestamp with time zone" json:"check_in_at"`
	ReminderSentAt   *time.Time     `gorm:"column:reminder_sent_at;type:timestamp with time zone" json:"reminder_sent_at"`
	AlertTriggeredAt *time.Time     `gorm:"column:alert_triggered_at;type:timestamp with time zone" json:"alert_triggered_at"`
}

// TableName DailyCheckIn's table name
func (*DailyCheckIn) TableName() string {
	return TableNameDailyCheckIn
}
