// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJourney = "journeys"

// Journey mapped from table <journeys>
type Journey struct {
	ID                 int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt          time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	UserID             int64          `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	Title              string         `gorm:"column:title;type:character varying(64);not null" json:"title"`
	Note               string         `gorm:"column:note;type:character varying(255);not null" json:"note"`
	ExpectedReturnTime time.Time      `gorm:"column:expected_return_time;type:timestamp with time zone;not null" json:"expected_return_time"`
	ActualReturnTime   *time.Time     `gorm:"column:actual_return_time;type:timestamp with time zone" json:"actual_return_time"`
	Status             string         `gorm:"column:status;type:character varying(16);not null;default:ongoing" json:"status"`
	ReminderSentAt     *time.Time     `gorm:"column:reminder_sent_at;type:timestamp with time zone" json:"reminder_sent_at"`
	AlertTriggeredAt   *time.Time     `gorm:"column:alert_triggered_at;type:timestamp with time zone" json:"alert_triggered_at"`
	AlertStatus        string         `gorm:"column:alert_status;type:character varying(16);not null;default:pending" json:"alert_status"`
	AlertAttempts      int64          `gorm:"column:alert_attempts;type:bigint;not null" json:"alert_attempts"`
	AlertLastAttemptAt *time.Time     `gorm:"column:alert_last_attempt_at;type:timestamp with time zone" json:"alert_last_attempt_at"`
}

// TableName Journey's table name
func (*Journey) TableName() string {
	return TableNameJourney
}
