// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNotificationTask = "notification_tasks"

// NotificationTask mapped from table <notification_tasks>
type NotificationTask struct {
	ID               int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	TaskCode         int64          `gorm:"column:task_code;type:bigint;not null" json:"task_code"`
	UserID           int64          `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	ContactPriority  *int16         `gorm:"column:contact_priority;type:smallint" json:"contact_priority"`
	ContactPhoneHash *string        `gorm:"column:contact_phone_hash;type:character(64)" json:"contact_phone_hash"`
	Category         string         `gorm:"column:category;type:character varying(32);not null" json:"category"`
	Channel          string         `gorm:"column:channel;type:character varying(16);not null" json:"channel"`
	Payload          string         `gorm:"column:payload;type:jsonb;not null" json:"payload"`
	Status           string         `gorm:"column:status;type:character varying(16);not null;default:pending" json:"status"`
	RetryCount       int16          `gorm:"column:retry_count;type:smallint;not null" json:"retry_count"`
	ScheduledAt      time.Time      `gorm:"column:scheduled_at;type:timestamp with time zone;not null" json:"scheduled_at"`
	ProcessedAt      *time.Time     `gorm:"column:processed_at;type:timestamp with time zone" json:"processed_at"`
	CostCents        int64          `gorm:"column:cost_cents;type:bigint;not null" json:"cost_cents"`
	Deducted         bool           `gorm:"column:deducted;type:boolean;not null" json:"deducted"`
}

// TableName NotificationTask's table name
func (*NotificationTask) TableName() string {
	return TableNameNotificationTask
}
