// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameQuotaTransaction = "quota_transactions"

// QuotaTransaction mapped from table <quota_transactions>
type QuotaTransaction struct {
	ID              int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt       time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	UserID          int64          `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	Channel         string         `gorm:"column:channel;type:character varying(16);not null" json:"channel"`
	TransactionType string         `gorm:"column:transaction_type;type:character varying(16);not null" json:"transaction_type"`
	Reason          string         `gorm:"column:reason;type:character varying(16);not null" json:"reason"`
	Amount          int64          `gorm:"column:amount;type:bigint;not null" json:"amount"`
	BalanceAfter    int64          `gorm:"column:balance_after;type:bigint;not null" json:"balance_after"`
}

// TableName QuotaTransaction's table name
func (*QuotaTransaction) TableName() string {
	return TableNameQuotaTransaction
}
