// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                     int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt              time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	UpdatedAt              time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;default:now()" json:"updated_at"`
	DeletedAt              gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone" json:"deleted_at"`
	PublicID               int64          `gorm:"column:public_id;type:bigint;not null" json:"public_id"`
	AlipayOpenID           string         `gorm:"column:alipay_open_id;type:character varying(64);not null" json:"alipay_open_id"`
	Nickname               string         `gorm:"column:nickname;type:character varying(64);not null" json:"nickname"`
	PhoneCipher            *[]uint8       `gorm:"column:phone_cipher;type:bytea" json:"phone_cipher"`
	PhoneHash              *string        `gorm:"column:phone_hash;type:character(64)" json:"phone_hash"`
	Status                 string         `gorm:"column:status;type:character varying(16);not null;default:waitlisted" json:"status"`
	EmergencyContacts      *string        `gorm:"column:emergency_contacts;type:jsonb;default:[]" json:"emergency_contacts"`
	Timezone               string         `gorm:"column:timezone;type:character varying(64);not null;default:Asia/Shanghai" json:"timezone"`
	DailyCheckInEnabled    bool           `gorm:"column:daily_check_in_enabled;type:boolean;not null" json:"daily_check_in_enabled"`
	DailyCheckInDeadline   string         `gorm:"column:daily_check_in_deadline;type:time without time zone;not null;default:20:00:00" json:"daily_check_in_deadline"`
	DailyCheckInGraceUntil string         `gorm:"column:daily_check_in_grace_until;type:time without time zone;not null;default:21:00:00" json:"daily_check_in_grace_until"`
	DailyCheckInRemindAt   string         `gorm:"column:daily_check_in_remind_at;type:time without time zone;not null;default:20:00:00" json:"daily_check_in_remind_at"`
	JourneyAutoNotify      bool           `gorm:"column:journey_auto_notify;type:boolean;not null;default:true" json:"journey_auto_notify"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
